# Generated by Django 4.1.2 on 2022-11-09 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_articulos_clientes_pedidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fechadealta',
        ),
    ]
