# Generated by Django 4.1.2 on 2022-11-09 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_usuario_fechadealta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cargo',
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
    ]
