# Generated by Django 4.1.2 on 2022-11-25 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_usuario_cargo_delete_cargo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedidos',
        ),
    ]
