# Generated by Django 4.1.2 on 2022-11-25 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_delete_pedidos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articulos',
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
