# Generated by Django 4.1.2 on 2022-11-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_pedidos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedidos',
        ),
    ]
