# Generated by Django 4.1.2 on 2022-11-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagoformas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_venta', models.DateField(verbose_name='Fecha de Venta')),
                ('monto', models.CharField(default=' ', max_length=100, verbose_name='Monto')),
                ('pagoformas', models.ManyToManyField(to='pagoformas.pagoforma')),
            ],
        ),
    ]
