# Generated by Django 4.1.2 on 2022-11-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=' ', max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, null=True, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
            ],
        ),
    ]
